package com.vtpl.forensic.vo;


/**
 * @author Tutai Kumar Dalal
 */
public interface VReturnValues {

	// GLOBAL
	int SUCCESS = 0;

	// Va engine related
	int VA_WARNING = 1;
	int VA_ERROR = 2;
	int VA_NULLPOINTER = 3;
	int VA_SIZEMISMATCH = 4;
	int VA_PARSINGFAILED = 5;
	int VA_WRONGFORMAT = 6;
	int VA_OUTOFBOUND = 7;
	int VA_INVALIDVALUE = 8;
	int VA_LOWBUFFERSIZE = 9;
	int VA_DATAYETNOTPREPARED = 10;
	int VA_LIBRARYYETNOTINITIALIZED = 11;
	int VA_LIBRARYALREADYINITIALIZED = 12;
	int VA_IMPROPERCALL = 13;
	int VA_VA_DUPLICATEID = 14;
	int VA_INVALIDID = 15;
	int VA_VALUENOTASSIGNED = 16;
	int VA_CALL_IGNORE		= 18;
	int VA_IGNORE = 19;

	int VA_PARAMETERNOTEXIST = 30;
	int VA_PARAMETEROUTOFBOUND = 31;
	int VA_PARAMETERNOTEDITABLE = 32;
	int VA_INVALIDPARAMETERVALUE = 33;
	int VA_WRONGPARAMETERSTRINGFORMAT = 34;
	int VA_MANDATORYPARAMETERSYETNOTSET = 35;
	int VA_INSUFFICIENTPARAMETERS = 36;
	int VA_NULLPARAMETER = 37;
	int VA_PARAMETERNOTSENT = 38;
	int VA_PARAMETERRECEIVEDSUCCESSFULLY = 39;
	int VA_PARAMETERSPARTIALLYACCEPTED = 40;
	int VA_INCOMPATIBLEPARAMETERS = 41;
	int VA_PARAMETERMULTIPLEDEFINITION = 42;

	int VA_INVALIDCOORDINATES = 55;
	int VA_INVALIDOPERATION = 56;
	int VA_INVALIDGRAPHICSTYPE = 57;
	int VA_TOOMANYOBJECTS = 58;
	int VA_INVALIDTOTALCONTROLPARAMETERS = 59;

	int VA_MEMORYOVERFLOW = 70;

	int VA_CHANNELNOTEXIST = 80;
	int VA_DUPLICATECHANNEL = 81;
	int VA_CHANNELOVERFLOW = 82;
	int VA_CHANNEL_STREAM_END = 83;

	int VA_TRYAGAIN = 100;
	int VA_WAIT = 101;
	int VA_BUSY = 102;
	int VA_SEARCH_COMPLETE = 103;

	int VA_EVALUATION_PERIOD_OVER = 150;
	int VA_CONTINUOUS_EVALUATION_OVER = 151;
	int VA_SYSTEM_FILE_CORRUPTED = 152;
	int VA_INVALID_HARDWARE = 153;
	int VA_VALIDITY_EXPIRED = 154;
	int VA_SYS_DATE_ELAPSED = 155;
	int VA_BEYOND_INS = 156;
	int VA_NO_AVAI_LINS = 157;
	int VA_LICENSE_CHECK_FAILED = 158;

	int CALL_NOT_ALLOWED_IN_DR = 998;
	int CALL_NOT_IMPLEMENTED = 999;
	

	// Database related
	int DB_CONNECTION_ERROR = 1000;
	int DB_STATEMENT_ERROR = 1001;
	int DB_UNKNOWN_ERROR = 1002;
	int STORAGE_COMPONENT_NOT_AVAILABLE = 1003;
	int DB_SPRING_ERROR = 1004;
	int DB_DATA_FORMAT_ERROR = 1005;
	int DB_DUPLICATE_KEY_ERROR = 1006;

	// USER RELATED
	int USER_ALREADY_LOGED_IN = 1100;
	int USER_INVALID_USERNAME_PASSWORD = 1101;
	int USER_INVALID_SESSION = 1102;
	int USER_PERMISSION_DENIED = 1103;
	int USER_DETAILS_NOT_AVAILABLE = 1104;
	int USER_INVALID_PROFILE_AUTHENTICATION = 1105;
	int USER_PENDING_MESSAGE = 1106;
	int USER_INVALID_CLIENT_MACHINE = 1107;
	int PENDING_CHAT_MESSAGE = 1108;
	int USER_DEFAULT_USERNAME_PASSWORD = 1109;
	int USER_PASSWORD_WEAK = 1110;

	int DC_DR_REPLICATOR_NOT_AVAILABLE          = 1061;
	
	// PTZ CONTROL
	int PTZ_TOO_MANY_REQUEST = 1200;
	int PTZ_SESSION_OCCUPIED = 1201;
	int CAMERA_DRIVER_NOT_AVAILABLE = 1202;
	int CAMERA_PARAMETER_NOT_SUPPORTED = 1203;

	// channel
	int CHANNEL_NOT_AVAILABLE = 1300;
	int CHANNEL_NUMBER_EXIST = 1301;
	int CHANNEL_OVERFLOW = 1302;
	int DUPLICATE_CHANNEL_REQUEST = 1303;
	int SNAP_NOT_AVIALBLE         = 1304;

	int RES_STORAGE_SPACE_AVAILABILITY_DATA_SEND_ERROR = 1901;

	// Recording details
	int RECORDING_PROFILE_NOT_AVAILABLE = 1400;

	int STORAGE_SERCHING_NOT_COMPLETED = 1450;
	int STORAGE_NOT_AVAILABLE = 1451;
	int STORAGE_LOW = 1452;

	int SSC_NULL_OBJECT_REQUEST = 1500;
	int SSC_ARGUMENT_MISMATCH = 1501;
	int SSC_TRUNCATED_OBJ_BYTES = 1502;
	int SSC_INVALID_REQUEST_ID = 1503;
	int SSC_CONNECTION_ERROR = 1504;
	int SSC_SENDING_REQUEST_ERROR = 1505;
	int SSC_ACCESS_RESPONSE_ERROR = 1506;
	int SSC_SERIALIZABLE_ERROR = 1507;
	int SSC_FILE_NOT_FOUND = 1508;
	int SSC_FILE_SIZE_OUT_OF_BOUND = 1509;
	int VA_CONNECTION_ERROR = 1510;
	int VA_REQUEST_ERROR = 1511;
	int VA_RESPONSE_ERROR = 1512;
	int VA_WRAPPER_NOT_AVAILABLE = 1513;
	
	int MEDIA_SERVER_CONNECTION_ERROR = 1514;
	int MEDIA_SERVER_SENDING_REQUEST_ERROR = 1515;
	int MEDIA_SERVER_ACCESS_RESPONSE_ERROR = 1516;
	
	int SUMMARIZATION_SERVER_CONNECTION_ERROR = 1517;
	int SUMMARIZATION_SERVER_SENDING_REQUEST_ERROR = 1518;
	int SUMMARIZATION_SERVER_ACCESS_RESPONSE_ERROR = 1519;
	
	int ATTRIBUTE_SEARCH_SERVER_CONNECTION_ERROR = 1517;
	int ATTRIBUTE_SEARCH_SERVER_SENDING_REQUEST_ERROR = 1518;
	int ATTRIBUTE_SEARCH_SERVER_ACCESS_RESPONSE_ERROR = 1519;
	

	int STREAMING_INVALID_REQUEST = 1550;
	int STREAMING_INVALID_SESSION = 1551;
	int STREAMING_INVALID_REQUEST_FORMAT = 1552;
	int SSC_VERSION_MISMATCH             = 1553;
	
	int CAMERA_LOAD_BALANCING_IS_GOING_ON = 1554;

	int RECORD_NOT_AVAILABLE = 1600;
	int MATRIX_SIZE_MISMATCH = 1601;

	int LICENSE_CHANNEL_OVER = 1700;
	int LICENSE_USER_OVER = 1701;
	int LICENSE_TIME_OVER = 1702;
	int WATCHDOG_CONNECTION_ERROR = 1703;
	int WATCHDOG_RESPONSE_ERROR = 1704;

	int INVALID_MEDIA_SERVER_ID = 1800;
	int MEDIASERVER_NOT_AVAILABLE = 1801;
	int SERVER_INTERFACE_NOT_AVAILABLE = 1802;
	int CHANNEL_RELATION_NOT_AVAILABLE = 1803;
	int NO_MEDIA_SERVER_AVAILABLE = 1804;
	int NVR_MODE_OFFLINE = 1805;
	int NVR_CONF_NOT_FOUND = 1806;
	int NVR_CHANNEL_NOT_REGISTERED = 1807;
	int INVALID_VMS_SERVER_ID = 1808;

	// REST Specific

	int SUCCESSFULLY_RETRIVED = 2000;
	int SUCCESSFULLY_UPDATED = 2001;
	int LOGIN_SUCCESSFUL = 2002;
	int LOGOUT_SUCCESSFUL = 2003;
	int WADL_GENERATION_SUCCESS = 2004;
	int SUCCESSFULLY_CREATED = 2005;
	int SUCCESSFULLY_DELETED = 2006;
	int SUCCESSFULLY_APPLIED = 2007;

	int HTTP_REST_CALL_EXCEPTION = 3000;

	int UNABLE_TO_RETRIVED = 3001;
	int UNABLE_TO_PROCESS = 3002;
	int UNKNOWN_RESOURCE_EXCEPTION = 3003;
	int NOT_IMPLEMENTED = 3004;
	int NOT_FOUND = 3005;
	int CLASS_NOT_FOUND = 3006;
	int MISSING_REQUEST_PARAMETER = 3007;
	int ILLEGAL_ARGUMENT = 3008;
	int NULL_POINTER_EXCEPTION = 3009;
	int RUNTIME_EXCEPTION = 3010;
	int DATA_ACCESS_EXCEPTION = 3011;

	int MISSING_VMSSESSIONID = 3100;
	int NO_USER = 3101;
	int NO_PROFILE = 3102;
	int NO_ENTERPRISE = 3103;
	int NO_LOCATION = 3104;
	int NO_VMSIP = 3105;
	int INVALID_IP_ADDRESS = 3106;
	int INVALID_EMAIL_ADDRESS = 3107;
	int INVALID_PHONENUMBER = 3108;
	int INVALID_POSTALCODE = 3109;
	int NO_CHANNEL = 3110;
	int INVALID_USER_PASSWORD = 3111;
	int CENTRAL_SESSION_ACTIVE = 3112;
	int INVALID_CENTRAL_SESSION = 3113;
	int USER_NOT_ASSIGNED_TO_SITE = 3114;
	int NO_ACTIVE_SITE_SESSION = 3115;
	int NOT_CENTRAL_ADMIN = 3116;
	int USER_EXISTS = 3117;
	int NOT_ALLOWED_TO_MODIFY_ANOTHER_ADMIN = 3118;
	int PASSWORD_BLANK = 3119;
	int CAN_NOT_DELETE_SELF = 3120;
	int CREATE_USER_ID_MISMATCH = 3121;
	int MISSING_EMAIL_ID = 3124;
	int MISSING_MOBILE_NUMBER = 3125;
	int MISSING_PHONE_NUMBER = 3126;
	int MISSING_VMSIP = 3127;
	int PARTIALLY_ASSIGNED_SITES = 3128;
	int HTTP_METHOD_IS_NOT_ALLOWED = 3129;
	int USER_SITE_ASSIGNMENT_EXISTS = 3130;
	int PARTIALLY_UPDATED_PASSWORD = 3131;
	int NOT_CENTRAL_SUPER_ADMIN = 3132;
	int PARTIALLY_SUCCESSFUL_TO_DELETE = 3133;
	int PARTIALLY_DELETED_SITES = 3134;
	int NO_SITE = 3135;
	int LOGOUT_PARTIAL = 3136;
	int NO_VA_SERVER = 3137;
	int MISSING_VASIP = 3138;
	int MISSING_POST_BODY = 3139;
	int FILE_SIZE_LIMIT_EXCEEDED = 3140;
	int INVALID_IMAGE_FILE = 3141;
	int NO_MAP = 3142;
	int RESOURCE_ALREADY_EXISTS = 3143;
	int NOT_CENTRAL_OPERATOR = 3144;
	int INVALID_ANALYTIC_ID = 3145;
	int MISSING_SITE_ID = 3146;
	int MISSING_HOUR_MIN_SEC = 3147;
	int MISSING_DAY_OF_WEEK = 3148;
	int MISSING_DAY_OR_MONTH = 3149;
	int NOT_ALLOWED = 3150;
	int INVALID_REPORT_TYPE = 3151;
	int MISSING_SCHEDULE_TYPE = 3152;
	int MISSING_SCHEDULE_FROM_TO = 3153;
	int INVALID_SCHEDULE_FROM_TO = 3154;
	int CENTRAL_SESSION_DISABLED = 3155;
	//int SITE_SESSION_DISABLED = 3156;
	int MISSING_MULTIPART_DATA = 3157;
	int SITE_NOT_ASSIGNED_TO_ENTERPRISE = 3158;
	int SITE_ALREADY_ASSIGNED = 3159;
	int USER_ALREADY_ASSIGNED = 3160;
	int INVALID_PASSWORD_RESET_KEY = 3161;
	int CAN_NOT_CONNECT_VMS_OR_INVALID_VMSIP = 3162;
	int MISSING_SCHEDULE_PARAMETER = 3163;
	int SITE_VMS_IP_ALREADY_EXISTS = 3164;
	int INVALID_ANALYTIC_SCHEDULE = 3165;
	int MISSING_ZONE_ROI = 3166;
	int INVALID_ZONE_ROI = 3167;
	int CAMERA_SEARCH_SERVER_NOT_CONNECTED = 3168;
	int INVALID_CAMERA_SEARCH_PARAMETER = 3169;
	int FAILED_SEND_CAMERA_SEARCH_PARAMETER = 3170;
	int LOGOUT_FAILURE = 3122;
	int MISSING_ADD_ENTERPRISE_PARAMETER = 3123;
	int NO_SCHEDULE = 3171;
	int INVALID_REQUEST_PARAMETER = 3172;
	int NOT_ALLOWED_SITE_VMS_IP_UPDATE = 3173;
	int NOT_ALLOWED_ENTERPRISE_NAME_UPDATE = 3174;
	int INVALID_PASSWORD_SEQURITY_QUES_ANS_SET = 3175;
	int UNAUTHORIZED_RESOURCE_ACCESS = 3176;
	int NOT_ENTERPRISE_ADMIN = 3177;
	int PASSWORD_MISMATCH = 3178;
	int INVALID_LOITERING_ZONE = 3179;
	int INVALID_UO_OR_ZONE = 3180;
	int LICENSE_ENTERPRISE_OVER = 3181;
	int MAX_ALLOWED_REPORT_QUERY_DAYS_EXCEEDED = 3182;
	int MIN_ALLOWED_REPORT_QUERY_DAYS_EXCEEDED = 3183;
	int NOT_ALLOWED_FUTURE_DATE = 3184;
	int INVALID_DOWNTIME_HOURS = 3185;
	int NOT_FOUND_CAMERA_REGISTRATION_MACID = 3186;
	int ALREADY_CAMERA_REGISTRATION_EXISTS = 3187;
	int QR_CODE_NOT_FOUND = 3188;
	int QR_CODE_INVALID = 3189;
	int QR_CODE_NOT_MATCHED = 3190;
	int QR_CODE_ALREADY_MATCHED = 3191;
	int QR_CODE_ALREADY_MATCHED_AND_CONNECTED_TO_VMS = 3192;
	int QR_CODE_GENERATION_ERROR = 3193;
	int NOT_AVAILAVLE_PASSWORD_RECOVERY_OPTIONS = 3194;
	int NO_VIRTUAL_UNIT = 3195;
	int UNABLE_TO_SPAWN_NEW_VIRTUAL_UNIT = 3196;
	int SUBSCRIBER_CAMERA_SERVICES_NOT_RUNNING = 3197;
	int SUBSCRIBER_CAMERA_SERVICES_SUSPENDED = 3198;
	int CLIP_DOWNLOAD_MAX_LIMIT_10MINS = 3199;
	int ANALYTICS_EXISTS = 3200;
	int ANALYTICS_SERVER_NOT_RUNNING = 3201;
	int ACCOUNT_ACTIVATION_PENDING = 3202;
	int ACCOUNT_SUSPENDED = 3203;
	int INVALID_PORT = 3204;
	int NOT_ALLOWED_TO_MODIFY_USER_ACCOUNT = 3205;
	int STATUS_UPDATE_FAILED = 3206;
	int DB_REDIS_CONNECTION_ERROR = 3207;
	int NO_EVENT_TAG = 3208;
	int SERVER_BUSY = 3209;
	int STOP_REGISTRATION_REQUEST = 3210;
	int REGISTRATION_REQUEST_ACCEPTED = 3211;
	
	int ALL_EDGE_DEVICE_NOT_REVOKED = 3212;
	int PROBLEM_IN_REVOKE_ENTERPRISE = 3213;
	
	int VDEVICE_SUCCESS = 3500;
	int VDEVICE_INVALID_CALL_ID = 3501;
	int VDEVICE_INVALID_DEVICE_ID = 3502;
	int VDEVICE_CALL_NOT_IMPLEMENTED = 3503;
	int VDEVICE_INVALID_STREAM_TYPE = 3504;
	int VDEVICE_INVALID_CODEC_TYPE = 3505;
	int VDEVICE_INVALID_WIDTH = 3506;
	int VDEVICE_INVALID_HEIGHT = 3507;
	int VDEVICE_INVALID_IP_RATE = 3508;
	int VDEVICE_INVALID_BIT_RATE_MODE = 3509;
	int VDEVICE_INVALID_FPS = 3510;
	int VDEVICE_INVALID_BITRATE = 3511;
	int VDEVICE_INVALID_BRIGHTNESS = 3512;
	int VDEVICE_INVALID_CONTRAST = 3513;
	int VDEVICE_INVALID_HUE = 3514;
	int VDEVICE_INVALID_IRIS_MODE = 3515;
	int VDEVICE_INVALID_SATURATION = 3516;
	int VDEVICE_INVALID_RESOLUTION = 3517;
	int VDEVICE_ERROR = 3518;
	
	
	int HLS_SERVER_WEB_ROOT_DIR_INVALID = 3550;
	int HLS_INVALID_SESSION = 3551;
	int HLS_UNKNOWN_ERROR = 3552;
	int HLS_STREAM_SOURCE_NOT_SUPPORTED = 3553;
	int HLS_STREAM_SOURCE_INACCESSIBLE = 3554;
	int HLS_IVMS_API_CONNECTION_ERROR = 3555;
	int STREAM_SOURCE_INACCESSIBLE = 3556;
	
	int ITMS_SITE_ASSIGNMENT_NOT_ALLOWED = 3600;
	int MISSING_DEVICE_NAME = 3601;
	int INVALID_MOBILE_NUMBER = 3602;
	int INVALID_DEVICE_TYPE = 3603;
	int USER_LOGIN_ALERT = 3604;
	
	int PASSWORD_HISTORY_MATCH = 3605;
	
	int PROBLEM_IN_CREATING_BUCKET = 3606;
	
	int PROBLEM_IN_GETTING_BUCKET_LIST = 3607;
	
	// itms-apiserver
	int REDIS_DB_CONNECTION_ERROR = 5000;
	int ITMS_TRIGGER_SEARCH_MAX_EVENTS_OVER = 4001;

	// RCS
	int INVALID_RCS_SERVER_ID = 6000;
	int RCS_NOT_AVAILABLE = 6001;
	int NO_RCS_SERVER_AVAILABLE = 6002;
	int ENCODING_SERVER_BUSY = 4002;
	int CHANNEL_CAPACITY_NOT_AVAILABLE = 4003;
	
	//VOC
	int ALERT_MESSAGING_GROUP_IN_USE = 4004;
	
	int VOC_AGENT_STATUS_CAMERA_DISCONNECT = 8000;
	int VOC_AGENT_STATUS_CAMERA_CONNECT = 8001;
	int VOC_AGENT_STATUS_AGENT_DISCONNECT = 8002;
	int VOC_AGENT_STATUS_AGENT_CONNECT = 8003;
	int VOC_AGENT_STATUS_STORAGE_FULL = 8004;
	
	int NAME_ALREADY_IN_USE = 8005;
	int INVALID_DATA_ACCESS_API_USAGE_EXCEPTION = 8006;
	
	
	// Track Chain 
	int TRCK_CHAIN_SERVICE_NOT_AVAILABLE = 9000;
	int PROBLEM_IN_TRCK_CHAIN_SERVICE    = 9001;
	
	// PTZ Pattern
	int PATTERN_NAME_ALREADY_IN_USE = 9002;
	int PATTERN_NAME_MANDATORY    = 9003;
	int PATTERN_DOES_NOT_EXIST    = 9004;
	
	int API_SERVER_NOT_CONFIGURED    = 9100;
	int NO_MEDIASERVER_LIVE			= 9101;
	int CAMERA_OFFLINE			= 9102;
	
	int HIVE_MQ_CONNECTION_ERROR			= 9103;
	int RABBIT_MQ_CONNECTION_ERROR			= 9104;
	
}